Jotex/Models/ServiceListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Jotex.Models
{
	public class ServiceListViewModel
	{
		public ServiceViewModel Service { get; set; }
	}
}

Jotex/Models/ServiceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Jotex.Models
{
	public class ServiceViewModel
	{
		public int Id { get; set; }
		public string Name { get; set; }

	}
}

Jotex/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Jotex.Controllers
{
    public class BlogController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Blog()
        {
            return View();
        }
        public IActionResult BlogFullWidth()
        {
            return View();
        }

        public IActionResult BlogSingle()
        {
            return View();
        }
    }
}

Jotex/Controllers/CaseStudiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Jotex.Controllers
{
    public class CaseStudiesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Jotex/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Jotex.Models;

namespace Jotex.Controllers
{
	public class HomeController : Controller
	{
	

		public IActionResult Index()
		{
			return View();
		}
		public IActionResult AboutUs()
		{
			return View();
		}
		public IActionResult Contact()
		{
			return View();
		}
		public IActionResult FAQ()
		{
			return View();
		}


	}
}

Jotex/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Jotex.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Jotex/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Jotex.Models;
using JotexRepository.InsuranceRepositories;
using JotexRepository.Models;
using Microsoft.AspNetCore.Mvc;

namespace Jotex.Controllers
{
    public class ServiceController : Controller
    {
        private readonly IMapper _mapper;

        private readonly IServiceRepository _serviceRepository;
        public ServiceController(IMapper mapper, IServiceRepository serviceRepository)
        {
            _mapper = mapper;
            _serviceRepository = serviceRepository;
        }
        public IActionResult Index(int id)
        {
            var service = _serviceRepository.GetServicesById(id);
            if (service == null) return NotFound();

            var model = new ServiceListViewModel
            {
                Service = _mapper.Map<Service, ServiceViewModel>(service)
            };
            return View(model);
        }
        public IActionResult ServiceView()
        {
            return View();
        }

    }
}

Jotex/ViewComponents/MenuViewComponent.cs
using AutoMapper;
using Jotex.Models;
using JotexRepository.InsuranceRepositories;
using JotexRepository.TestimonialRepositories;
using JotexRepository.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Jotex.ViewComponents
{
	public class MenuViewComponent:ViewComponent
	{
		private readonly IMapper _mapper;
		private readonly ServiceRepository _serviceRepository;
		public MenuViewComponent(IMapper mapper, ServiceRepository serviceRepository)
		{
			_mapper = mapper;
			_serviceRepository = serviceRepository;
		}
		public IViewComponentResult Invoke() 
		{
			var services = _serviceRepository.GetServices();

			var model = _mapper.Map<IEnumerable<Service>,IEnumerable<ServiceViewModel>>(services);
			return View(model);

		}
	}
}

Jotex/Views/Blog/Blog.cshtml
@{
    ViewData["Title"] = "Blog";
}

<section class="page-title">
    <div class="page-title-container">
        <div class="page-title-wrapper">
            <div class="container">
                <div class="row">
                    <div class="col col-xs-12">
                        <h2>Blog</h2>
                        <ol class="breadcrumb">
                            <li><a href="index.html">Home</a></li>
                            <li>Blog</li>
                        </ol>
                    </div>
                </div> <!-- end row -->
            </div> <!-- end container -->
        </div>
    </div>
</section>
<section class="blog-pg-section section-padding">
    <div class="container">
        <div class="row">
            <div class="col col-md-8">
                <div class="blog-content">
                    <div class="post format-standard-image">
                        <div class="entry-media">
                            <img src="assets/images/blog/img-2.jpg" alt>
                        </div>
                        <ul class="entry-meta">
                            <li><a href="#"><i class="fi flaticon-user"></i> By: Admin</a></li>
                            <li><a href="#"><i class="fi flaticon-tag-1"></i> Insurance, company</a></li>
                            <li><a href="#"><i class="fi flaticon-calendar"></i>11 March 2020</a></li>
                        </ul>
                        <h3><a href="#">And you can design with tons of artwork and fonts you won’t find anywhere</a></h3>
                        <p>Samma game samples lay spread out on the table samsa was a travelling salesman - and above it there hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame. It showed a lady fitted out with</p>
                        <a href="#" class="theme-btn-s3">Read More</a>
                    </div>
                    <div class="post format-standard">
                        <ul class="entry-meta">
                            <li><a href="#"><i class="fi flaticon-user"></i> By: Admin</a></li>
                            <li><a href="#"><i class="fi flaticon-tag-1"></i> Insurance, company</a></li>
                            <li><a href="#"><i class="fi flaticon-calendar"></i>11 March 2020</a></li>
                        </ul>
                        <h3><a href="#">your insurance company looking for a catchy nowadays</a></h3>
                        <p>Samma game samples lay spread out on the table samsa was a travelling salesman - and above it there hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame. It showed a lady fitted out with</p>
                        <a href="#" class="theme-btn-s3">Read More</a>
                    </div>
                    <div class="post format-gallery">
                        <div class="entry-media post-slider">
                            <img src="assets/images/blog/img-3.jpg" alt>
                            <img src="assets/images/blog/img-2.jpg" alt>
                        </div>
                        <ul class="entry-meta">
                            <li><a href="#"><i class="fi flaticon-user"></i> By: Admin</a></li>
                            <li><a href="#"><i class="fi flaticon-tag-1"></i> Insurance, company</a></li>
                            <li><a href="#"><i class="fi flaticon-calendar"></i>11 March 2020</a></li>
                        </ul>
                        <h3><a href="#">And you can design with tons of artwork and fonts you won’t find anywhere</a></h3>
                        <p>Samma game samples lay spread out on the table samsa was a travelling salesman - and above it there hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame. It showed a lady fitted out with</p>
                        <a href="#" class="theme-btn-s3">Read More</a>
                    </div>
                    <div class="post format-quote">
                        <ul class="entry-meta">
                            <li><a href="#"><i class="fi flaticon-user"></i> By: Admin</a></li>
                            <li><a href="#"><i class="fi flaticon-tag-1"></i> Insurance, company</a></li>
                            <li><a href="#"><i class="fi flaticon-calendar"></i>11 March 2020</a></li>
                        </ul>
                        <h3><a href="#">Insurance company looking for a dash</a></h3>
                        <p>Samma game samples lay spread out on the table samsa was a travelling salesman - and above it there hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame. It showed a lady fitted out with</p>
                        <a href="#" class="theme-btn-s3">Read More</a>
                    </div>
                    <div class="post format-video">
                        <div class="entry-media video-holder">
                            <img src="assets/images/blog/img-4.jpg" alt>
                            <a href="https://www.youtube.com/embed/7e90gBu4pas?autoplay=1" class="video-btn" data-type="iframe">
                                <i class="fi flaticon-play"></i>
                            </a>
                        </div>
                        <ul class="entry-meta">
                            <li><a href="#"><i class="fi flaticon-user"></i> By: Admin</a></li>
                            <li><a href="#"><i class="fi flaticon-tag-1"></i> Insurance, company</a></li>
                            <li><a href="#"><i class="fi flaticon-calendar"></i>11 March 2020</a></li>
                        </ul>
                        <h3><a href="#">And you can design with tons of artwork and fonts you won’t find anywhere</a></h3>
                        <p>Samma game samples lay spread out on the table samsa was a travelling salesman - and above it there hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame. It showed a lady fitted out with</p>
                        <a href="#" class="theme-btn-s3">Read More</a>
                    </div>
                    <div class="pagination-wrapper pagination-wrapper-left">
                        <ul class="pg-pagination">
                            <li>
                                <a href="#" aria-label="Previous">
                                    <i class="fi flaticon-back"></i>
                                </a>
                            </li>
                            <li class="active"><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li>
                                <a href="#" aria-label="Next">
                                    <i class="fi flaticon-next"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col col-md-4">
                <div class="blog-sidebar">
                    <div class="widget about-widget">
                        <h3>About us</h3>
                        <div class="img-holder">
                            <img src="assets/images/blog/about-widget.jpg" alt>
                        </div>
                        <p>Samples lay spread out on the Samsa was a travelling salesman and above it there hung and null about  that he</p>
                        <div class="social">
                            <ul class="clearfix">
                                <li><a href="#"><i class="ti-facebook"></i></a></li>
                                <li><a href="#"><i class="ti-twitter-alt"></i></a></li>
                                <li><a href="#"><i class="ti-linkedin"></i></a></li>
                                <li><a href="#"><i class="ti-pinterest"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="widget search-widget">
                        <h3>Search</h3>
                        <form>
                            <div>
                                <input type="text" class="form-control" placeholder="Search Post..">
                                <button type="submit"><i class="ti-search"></i></button>
                            </div>
                        </form>
                    </div>
                    <div class="widget category-widget">
                        <h3>Categories</h3>
                        <ul>
                            <li><a href="#">Life Insurance <span>(2)</span></a></li>
                            <li><a href="#">Home Insurance <span>(5)</span></a></li>
                            <li><a href="#">Health Insurance <span>(12)</span></a></li>
                            <li><a href="#">Property insurance  <span>(5)</span></a></li>
                            <li><a href="#">Fire Insurance <span>(8)</span></a></li>
                        </ul>
                    </div>
                    <div class="widget recent-post-widget">
                        <h3>Recent post</h3>
                        <div class="posts">
                            <div class="post">
                                <div class="img-holder">
                                    <img src="assets/images/recent-posts/img-1.jpg" alt>
                                </div>
                                <div class="details">
                                    <h4><a href="#">For your insurance business, employees, or clients</a></h4>
                                    <span class="date">11 March 2020</span>
                                </div>
                            </div>
                            <div class="post">
                                <div class="img-holder">
                                    <img src="assets/images/recent-posts/img-2.jpg" alt>
                                </div>
                                <div class="details">
                                    <h4><a href="#">Once you’ve picked your vorite, be sure to outfit your</a></h4>
                                    <span class="date">11 March 2020</span>
                                </div>
                            </div>
                            <div class="post">
                                <div class="img-holder">
                                    <img src="assets/images/recent-posts/img-3.jpg" alt>
                                </div>
                                <div class="details">
                                    <h4><a href="#">Be prepared for life’s Once you’ve picked your vorite</a></h4>
                                    <span class="date">11 March 2020</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="widget tag-widget">
                        <h3>Tags</h3>
                        <ul>
                            <li><a href="#">People</a></li>
                            <li><a href="#">Business</a></li>
                            <li><a href="#">Life insurance</a></li>
                            <li><a href="#">Poll insurance</a></li>
                            <li><a href="#">Car insurance</a></li>
                            <li><a href="#">Manfacturing</a></li>
                        </ul>
                    </div>
                    <div class="widget ad-widget">
                        <h3>Advertising Spot</h3>
                        <div class="img-holder">
                            <a href="#"><img src="assets/images/blog/ad-img.jpg" alt></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- end container -->
</section>
<!-- end blog-pg-section -->

Jotex/Views/Shared/Components/Menu/Default.cshtml
@model  IEnumerable<ServiceViewModel>
<nav class="navigation navbar navbar-default">
    <div class="separator-bottom"></div>
    <div class="separator-bottom-2"></div>
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="open-btn">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html"><img src="~/images/logo.png" alt></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse navbar-left navigation-holder">
            <div class="left-separator"></div>
            <button class="close-navbar"><i class="ti-close"></i></button>
            <ul class="nav navbar-nav">
                <li class="menu-item-has-children current-menu-parent">
                    <a href="#">Home</a>
                    <ul class="sub-menu">
                        <li class="current-menu-item"><a href="index.html">Home style 1</a></li>
                        <li><a href="index-2.html">Home style 2</a></li>
                        <li><a href="index-3.html">Home style 3</a></li>
                        <li><a href="index-4.html">Home style 4</a></li>
                    </ul>
                </li>
                <li class="menu-item-has-children">
                    <a href="#">Pages</a>
                    <ul class="sub-menu">
                        <li><a asp-controller="Home" asp-action="AboutUs">About us</a></li>
                        <li><a asp-controller="Home" asp-action="Contact">Contact us</a></li>
                        <li><a href="awards.html">Awards</a></li>
                        <li><a href="pricing-plan.html">Pricing plan</a></li>
                        <li><a href="testimonials.html">Testimonials</a></li>
                        <li><a href="testimonials-s2.html">Testimonials style 2</a></li>
                        <li><a href="team.html">Team</a></li>
                        <li><a asp-controller="Home" asp-action="FAQ">FAQ</a></li>
                        <li><a href="404.html">404</a></li>
                    </ul>
                </li>
                <li class="menu-item-has-children">
                    <a href="#">Services</a>
                    <ul class="sub-menu">
                        @foreach (var service in Model)
                                        {
                            <li><a href="services.html">@service.Name</a></li>
                            @*<li><a href="services-s2.html">Services style 2</a></li>
                            <li><a href="service-single.html">Life insurance</a></li>
                            <li><a href="car-insurance.html">Car insurance</a></li>
                            <li><a href="home-insurance.html">Home insurance</a></li>
                            <li><a href="health-insurance.html">Helth insurance</a></li>
                            <li><a href="investment-plan.html">Investment plan</a></li>
                            <li><a href="life-insurance.html">Life insurance</a></li>**@
                        }

                    </ul>
                </li>
                <li class="menu-item-has-children">
                    <a href="#">Case studies</a>
                    <ul class="sub-menu">
                        <li><a asp-controller="CaseStudies" asp-action="CaseStudies">Case studies</a></li>
                        <li><a asp-controller="CaseStudies" asp-action="CaseStudiesSingle">Case studies single</a></li>
                    </ul>
                </li>
                <li class="menu-item-has-children">
                    <a asp-controller="Blog" asp-action="Blog">Blog</a>
                    <ul class="sub-menu">
                        <li class="menu-item-has-children">
                            <a href="#Level3">Blog listing</a>
                            <ul class="sub-menu">
                                <li><a asp-controller="Blog" asp-action="BlogFullWidth">Full width</a></li>
                            </ul>
                        </li>
                        @*<li class="menu-item-has-children">
                                <a href="#Level3">Blog grid</a>
                                <ul class="sub-menu">
                                    <li><a href="blog-grid-2-columns.html">2 columns</a></li>
                                    <li><a href="blog-grid-2-columns-sidebar.html">2 columns sidebar</a></li>
                                    <li><a href="blog-grid-3-columns.html">3 columns</a></li>
                                    <li><a href="blog-grid-4-columns.html">4 columns</a></li>
                                </ul>
                            </li>
                            <li class="menu-item-has-children">
                                <a href="#Level3">Blog masonry</a>
                                <ul class="sub-menu">
                                    <li><a href="blog-masonry-2-columns.html">2 columns</a></li>
                                    <li><a href="blog-masonry-2-columns-sidebar.html">2 columns sidebar</a></li>
                                    <li><a href="blog-masonry-3-columns.html">3 columns</a></li>
                                    <li><a href="blog-masonry-4-columns.html">4 columns</a></li>
                                </ul>
                            </li>
                            <li class="menu-item-has-children">
                                <a href="#Level3">Blog single</a>
                                <ul class="sub-menu">
                                    <li><a href="blog-single.html">Right sidebar</a></li>
                                    <li><a href="blog-single-left-sidebar.html">Left sidebar</a></li>
                                    <li><a href="blog-single-full-width.html">Full width</a></li>
                                </ul>
                            </li>*@
                    </ul>
                </li>
                <li><a href="contact.html">Contact</a></li>
            </ul>
        </div><!-- end of nav-collapse -->

        <div class="search-contact">
            <div class="contact">
                <a href="#">
                    <i class="fi flaticon-feedback"></i>
                    <h5>Have any query?</h5>
                    <span>++8891682000000</span>
                </a>
            </div>
            <div class="header-search-area">
                <div class="header-search-form">
                    <form class="form">
                        <div>
                            <input type="text" class="form-control" placeholder="Search here">
                        </div>
                        <button type="submit" class="btn"><i class="ti-search"></i></button>
                    </form>
                </div>
                <div>
                    <button class="btn open-btn"><i class="ti-search"></i> <span>Search</span></button>
                </div>
            </div>
        </div>

    </div><!-- end of container -->
</nav>

Jotex/Views/Shared/Page/Title.cshtml
<!-- start page-title -->
<section class="page-title">
    <div class="page-title-container">
        <div class="page-title-wrapper">
            <div class="container">
                <div class="row">
                    <div class="col col-xs-12">
                        <h2>@ViewData["Title"]</h2>
                        <ol class="breadcrumb">
                            <li><a href="index.html">Home</a></li>
                            <li>@ViewData["Title"]</li>
                        </ol>
                    </div>
                </div> <!-- end row -->
            </div> <!-- end container -->
        </div>
    </div>
</section>
<!-- end page-title -->

Jotex/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from themegeniuslab.com/html/jotex-live-cp/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 14 May 2020 15:22:11 GMT -->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="author" content="irstheme">

	<title> @ViewData["index"]</title>

	<link href="~/css/themify-icons.css" rel="stylesheet">
	<link href="~/css/flaticon.css" rel="stylesheet">
	<link href="~/css/bootstrap.min.css" rel="stylesheet">
	<link href="~/css/animate.css" rel="stylesheet">
	<link href="~/css/owl.carousel.css" rel="stylesheet">
	<link href="~/css/owl.theme.css" rel="stylesheet">
	<link href="~/css/slick.css" rel="stylesheet">
	<link href="~/css/slick-theme.css" rel="stylesheet">
	<link href="~/css/swiper.min.css" rel="stylesheet">
	<link href="~/css/owl.transitions.css" rel="stylesheet">
	<link href="~/css/odometer-theme-default.css" rel="stylesheet">
	<link href="~/css/jquery.fancybox.css" rel="stylesheet">
	<link href="~/css/style.css" rel="stylesheet">

	@RenderSection("Head", required: false)

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>

<body>

	<header id="header" class="site-header header-style-1">
		<div class="topbar">
			<div class="container-fluid">
				<div class="row">
					<div class="col col-md-8">
						<div class="info">
							<ul>
								<li><i class="ti-location-pin"></i> 22/1 Rokon uddin sorok mistripara, Austr</li>
								<li><i class="ti-timer"></i> Mon - Sun 9.00am - 5 pm</li>
							</ul>
						</div>
					</div>
					<div class="col col-md-4">
						<div class="social-quote clearfix">
							<div class="social-links">
								<ul>
									<li><a href="#"><i class="ti-facebook"></i></a></li>
									<li><a href="#"><i class="ti-twitter-alt"></i></a></li>
									<li><a href="#"><i class="ti-linkedin"></i></a></li>
									<li><a href="#"><i class="ti-pinterest"></i></a></li>
									<li><a href="#"><i class="ti-vimeo-alt"></i></a></li>
								</ul>
							</div>
							<div class="quote-btn">
								<a href="#" class="theme-btn-s2">Get a quote <i class="fi flaticon-next"></i></a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div> <!-- end topbar -->

<vc:menu></vc:menu>
	</header>
	<!-- end of header -->
	<!-- start page-wrapper -->
	<div class="page-wrapper">

		<!-- start preloader -->
		<div class="preloader">
			<div class="spinner">
				<div class="double-bounce1"></div>
				<div class="double-bounce2"></div>
			</div>
		</div>
		<!-- end preloader -->
		<!-- Start header -->

		@RenderBody()
		<!-- start site-footer -->
		<footer class="site-footer">
			<div class="newsletter-area">
				<div class="container">
					<div class="row">
						<div class="col col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
							<div class="newsletter-inner clearfix">
								<div class="text">
									<h3>Newsletter</h3>
									<p>Get latest news & update</p>
								</div>
								<form>
									<div class="input-1">
										<input type="email" class="form-control" placeholder="Email Address *" required="">
									</div>
									<div class="submit clearfix">
										<button type="submit">Subcribe</button>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
				<div class="separator"></div>
			</div>
			<div class="upper-footer">
				<div class="container">
					<div class="row">
						<div class="col col-lg-3 col-md-3 col-sm-6">
							<div class="widget about-widget">
								<div class="widget-title">
									<h3>
										<span class="hidden">About us</span>
										<img src="~/images/footer-logo.png" alt>
									</h3>
								</div>
								<p>Showed a lady fitted out with a fur hat and fur boa who sat upright, raising a heavy</p>
								<div class="social-links">
									<ul>
										<li><a href="#"><i class="ti-facebook"></i></a></li>
										<li><a href="#"><i class="ti-twitter-alt"></i></a></li>
										<li><a href="#"><i class="ti-linkedin"></i></a></li>
										<li><a href="#"><i class="ti-pinterest"></i></a></li>
										<li><a href="#"><i class="ti-vimeo-alt"></i></a></li>
									</ul>
								</div>
							</div>
						</div>
						<div class="col col-lg-3 col-md-3 col-sm-6">
							<div class="widget contact-widget service-link-widget">
								<div class="widget-title">
									<h3>Address Location</h3>
								</div>
								<ul>
									<li>65/15 Old norok Avenew Booston town, Austria</li>
									<li><span>Phone:</span> 84667441</li>
									<li><span>Email:</span> demo@example.com</li>
									<li><span>Office Time:</span> 10AM- 5PM</li>
								</ul>
							</div>
						</div>
						<div class="col col-lg-3 col-md-3 col-sm-6">
							<div class="widget link-widget">
								<div class="widget-title">
									<h3>Quick Links</h3>
								</div>
								<ul>
									<li><a href="#">About us</a></li>
									<li><a href="#">Our services</a></li>
									<li><a href="#">Contact us</a></li>
									<li><a href="#">Meet team</a></li>
								</ul>
								<ul>
									<li><a href="#">Privacy Policy</a></li>
									<li><a href="#">Testimonials</a></li>
									<li><a href="#">News</a></li>
									<li><a href="#">FAQ</a></li>
								</ul>
							</div>
						</div>
						<div class="col col-lg-3 col-md-3 col-sm-6">
							<div class="widget agent-widget">
								<div class="widget-title">
									<h3>Need an agent?</h3>
								</div>
								<div class="content">
									<h4><a href="#"><i class="fi flaticon-agent"></i> Find it now</a></h4>
									<p>++6485757254</p>
								</div>
							</div>
						</div>
					</div>
				</div> <!-- end container -->
			</div>
			<div class="lower-footer">
				<div class="container">
					<div class="row">
						<div class="separator"></div>
						<div class="col col-xs-12">
							<p class="copyright">Copyright &copy; 2020 Jotex. All rights reserved</p>
							<div class="extra-link">
								<ul>
									<li><a href="#">Privace & Policy</a></li>
									<li><a href="#">terms and conditions</a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</footer>
		<!-- end site-footer -->



	</div>
	<!-- end of page-wrapper -->
	<!-- All JavaScript files
	================================================== -->
	<script src="~/js/jquery.min.js"></script>
	<script src="~/js/bootstrap.min.js"></script>

	<!-- Plugins for this template -->
	<script src="~/js/jquery-plugin-collection.js"></script>

	@RenderSection("Scripts", false)
	<!-- Custom script for this template -->
	<script src="~/js/script.js"></script>
</body>

<!-- Mirrored from themegeniuslab.com/html/jotex-live-cp/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 14 May 2020 15:22:50 GMT -->
</html>